import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ButterflyGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <div className="flex-grow">
          <div className="flex">
            <div className="w-1/5"></div> {/* Empty column */}
            <div className="w-3/5">{children}</div> {/* Middle column */}
            <div className="w-1/5"></div> {/* Empty column */}
          </div>
        </div>
      </body>
    </html>
  );
}
